var
	STATUS_SORT_DMI_MAP = "Not Started"
	STATUS_FIX_DMI1 = "Not Started"
	STATUS_FIX_DMI2 = "Not Started"

	STATUS_COMPARE_ICON = "Not Started"
	STATUS_FIND_DUPLICATE = "Not Started"

	STATUS_DMI2_MAP_PROCESS_1 = "Not Started"
	STATUS_DMI2_MAP_PROCESS_2 = "Not Started"
	STATUS_DMI2_MAP_PROCESS_3 = "Not Started"

proc/ResetStatus()
	STATUS_SORT_DMI_MAP = initial(STATUS_SORT_DMI_MAP)
	STATUS_FIX_DMI1 = initial(STATUS_FIX_DMI1)
	STATUS_FIX_DMI2 = initial(STATUS_FIX_DMI2)

	STATUS_COMPARE_ICON = initial(STATUS_COMPARE_ICON)
	STATUS_FIND_DUPLICATE = initial(STATUS_FIND_DUPLICATE)

	STATUS_DMI2_MAP_PROCESS_1 = initial(STATUS_DMI2_MAP_PROCESS_1)
	STATUS_DMI2_MAP_PROCESS_2 = initial(STATUS_DMI2_MAP_PROCESS_2)
	STATUS_DMI2_MAP_PROCESS_3 = initial(STATUS_DMI2_MAP_PROCESS_3)